//
//  FXDatabaseFactory.m
//  DeineMudda
//
//  Created by jrk on 22/9/10.
//  Copyright 2010 flux forge. All rights reserved.
//

#import "FXDatabaseFactory.h"
#import "FXManagedJoke.h"

@implementation FXDatabaseFactory

+ (void) createDatabase
{
	NSUserDefaults *defs = [NSUserDefaults standardUserDefaults];
	if ([defs boolForKey: @"databaseCreated"])
	{	
		NSLog(@"already created la db!");
		return;
	}


	NSArray *lolimport = [NSArray arrayWithObjects:
  						  @"Deine Mudda ist schwarz und fährt den Bus vom A-Team.",
						  @"Deine Mudda stinkt so hart, die hat ihr eigenes Ozonloch.",
						  @"Deine Mudda bellt wenn es klingelt.",
						  @"McDonald's hat angerufen, deine Mudda steckt mal wieder betrunken in der Rutsche fest.",
						  @"Deine Mudda ist wie Shrek: Dick, furzt immer und ist grün.",
						  @"Deine Mudda hat mehr Eicheln gesehn als der Förster im wald.",
						  @"Deine Mudda ist so fett,sie ging auf den Markt und wurde wegen illegaler Massenversammlung verhaftet.",
						  @"Wenn deine Mudda vor dem fernsehen vorbei läuft, verpasst du alle drei Herr der Ringe Teile.",
						  @"Das ist keine Vulkanasche-Wolke. Deine Mudda hat gefurzt.",
						  @"Deine Mudda is so dumm, die schaut bei ner Glastür durchs Schlüsselloch.",
						  @"Deine Mudda verleiht Brennholz.",
						  @"Deine Mudda ist so hässlich dein vater nimmt sie mit zur arbeit damit er kein abschieds kuss machen muß.",
						  @"Deine Mudda hat King Kong im schwitzkasten.",
						  @"Deine Mudda ist so fett, sie könnte eine zweite welt bilden.",
						  @"Deine Mudda schnallt sich einen Staubsauger auf den Rücken und ruft Ghost Busters.",
						  @"Deine Mudda benutzt nen fallschirm als Kopftuch.",
						  @"Deine Mudda geht zur Schule und singt dieser Weg wird kein leichter sein.",
						  @"Deine Mudda ist beim Bund.",
						  @"Deine Mudda ist so fett, sie spielt bei Godzilla die Hauptrolle.",
						  @"Deine Mudda ist so dumm, sie schminkt sich mit Edding.",
						  @"Deine Mudda ist Hülsensammlerin auf dem Übungsplatz.",
						  @"Deine Mudda ist so dumm wenn sie eine Tomate auf den boden schmeisst sagt sie pikachu komm raus.",
						  @"Deine Mudda gratuliert Chuck Noris nicht zum Geburtstag.",
						  @"Deine Mudda rasiert sich mit einem Rasenmäher die Beine.",
						  @"Deine Mudda packt sich eine Felge auf den Rücken und spielt Transformers.",
						  @"Deine Mudda heißt Gollum und will ihren Ehering wieder.",
						  @"Deine Mudda geht zu wer wird Millionaer um ein Glas Wasser zu trinken.",
						  @"Deine Mudda ist der Grund für den Weltuntergang im jahre 2012.",
						  @"Deine Mudda spielt die hauptrolle von zeiten ändern dich.",
						  @"Deine Mudda ist so Fett, wenn sie auf die Waage steht, steht da Fortsetzung folgt.",
						  @"Deine Mudda beantragt bei Monopoli Hartz4.",
						  @"Deine Mudda ruft bei Apple an und bestellt Obst.",
						  @"Deine Mudda ist so Dumm sie kukt auf die karte und findet Russland nicht.",
						  @"Deine Mudda hat 'nen Zickenbart und ist Chef der Al-Qaida.",
						  @"Deine Mudda verhütet mit der Glücksspirale.",
						  @"Deine Mudda hört sich im schlaf an wie Darth Vader und sagt zu dir: Ich bin dein Vater.",
						  @"Deine Mudda steht 5 vor 8 vor Aldi und singt this is the final countdown.",
						  @"Deine Mudda lässt Salat anbrennen.",
						  @"Deine Mudda arbeite aufm Fischkutter als Gestank.",
						  @"Deine Mudda läuft nackt durch die Stadt und schreit : DAS IST SPARTA.",
						  @"Deine Mudda ist so fett wenn sie sich umdreht hab ich alle teile von herr der ringe verpasst.",
						  @"Deine Mudda ist so blöd sie hockt auf den fernseh und guckt aufs sofa.",
						  @"Deine Mudda mach ein roundhousekick bei cuck norris.",
						  @"Deine Mudda ist so hässlich man kann das nicht beschreiben.",
						  @"Deine Mudda heißt Bruno und hat`n Namenschild in ihrem Trekker.",
						  @"Deine Mudda ist so fett, sie wird vom LKW angefahren und fragt: wer hat den stein geworfen?.",
						  @"Deine Mudda hätte dich besser schlucken sollen;).",
						  @"Deine Mudda fährt Dreirad bei Saw.",
						  @"Wenn deine Mudda Blät sagt dein vatter gesundheit.",
						  @"Deine Mudda Käuft sich ein Gameboy und ein würfel und sie sagt Ey habe Gamecube gekauft.",
						  @"Deine Muter arbeitet im Dönerladen und dreht sich.",
						  @"Deine Mudda hat schon mehr Eicheln gesehen als jeder Förster.",
						  @"Deine Mudda verteilt Treueherzen - auf dem Kiez.",
						  @"Deine Mudda ist wie ein Senfglas! Jeder Steckt sein Würstchen rein.",
						  @"Deine Mudda kommt mit 'ner schusssicheren Weste zu Russisch Roulette...",
						  @"Deine Mudda ist der Container von der neuen Big Brother Staffel.",
						  @"Deine Mudda macht die Ansagen in der S-Bahn.",
						  @"Deine Mudda geht zum Schweinestall und singt ''We are Family''.",
						  @"Deine Mudda klaut Strafzettel, die an Autoscheiben hängen.",
						  @"Die Sendung ''Ich bin ein Star, holt mich hier raus'' findet in den Achselhöhlen deiner Mudda statt.",
						  @"Deine Mudda schnitzt Möbel für Ikea.",
						  @"Deine Mudda lässt sich aufm Jahrmarkt für 50 Cent in die Eier treten.",
						  @"Backe Backe Kuchen, deine Mudda kann man buchen.",
						  @"Deine Mudda ist so häßlich da könnte vorn auch hinten sein.",
						  @"Deine Mudda steht vorm spiegel und sagt spieglein spieglein an der wand wer ist die schönste an der schönste im ganzem lang der spiegel antwortet geh zur seite ich seh nichts.",
						  @"Deine Mudda is so dumm die ist heute noch auf der suche nach den gewichten für die wasserwaage.",
						  @"Deine Mudda stinkt so krass dass nicht mal das Deo an sie ran will.",
						  @"Deine Mudda stellt sich nackt vor kik und schreit ich bin billiger.",
						  @"Deine Mudda arbeitet auf den bau als gegengewicht vom kran.",
						  @"Wenn deine Mudda furtzt sagt dein Vater Gesundheit.",
						  @"Deine Mudda spielt sich an den Brüsten und sagt “Man hab ich dicke Eier”.",
						  @"Der Gürtel deiner Mudda heißt Äquator.",
						  @"Dein Mudda bindet sich ein Fahrrad auf den Rücken und spielt im Garten transformers.",
						  @"Deine Mudda hat keine Zähne und versucht Snickers zu essen.",
						  @"Der Dönerladen hat angerufen, deine Mudda dreht sich nicht mehr.",
						  @"Deine Mudda klaut Aldi-Tüten bei Kik.",
						  @"Deine Mudda is so dumm, sie schmeißt ne orange auf dem Boden und sagt: Pikachu, du schaffst es !.",
						  @"Deine Mudda spielt hinterm lidl parkplatz um Pfandflaschen.",
						  @"Deine Mudda ist so dumm,sie stolpert über ein kabelloses telefon.",
						  @"Lass meine Mudda aus dem Spiel dann lass ich deine aus dem Keller.",
						  @"Deine Mudda ist so dumm, die erfindet Wasserdichte Teebeutel und einen Rollstuhl mit Pedale.",
						  @"Deine Mudda klaut Daten bei StudiVZ.",
						  @"Deine Mudda ist so dumm, sie kippt ein Actimel über den PC und glaubt er wäre vor Viren geschützt.",
						  @"Deine Mudda ist so dämlich sie löscht feurer mit bezin.",
						  @"Deine Mudda ist so fett, sie versperrt den weg nach Fuchsania City.",
						  @"Deine Mudda heißt Otfried und ist der Bulle von Tölz.",
						  @"Wenn der Geier ausstirbt ist deine Mudda der hässlichste Vogel der Welt.",
						  @"Deine Mudda Wird Nach 2Glässern Wasser besofen.",
						  @"Deine Mudda ist so fett, ihr Arsch bekommt von Unicef Entwicklungshilfe.",
						  @"Deine Mudda is so dumm, sie stolpert über ein schnurlos-telefon.",
						  @"Wenn deine Mudda frühs aufsteht,dann gibt es in China ein Erdbeben.",
						  @"Deine Mudda zerreißt Telefonbücher bei Wetten Dass.",
						  @"Deine Mudda is so dumm,die schnallt sich ein fahrrad auf den Rücken und spielt Transformers.",
						  @"Deine Mudda ist so fett, sie spielt den Todesstern in Star Wars.",
						  @"Deine Mudda guckt bei google earth ob sie pickel am arsch hat.",
						  @"Deine Mudda ist so dumm sie wird von Browsergames süchtig.",
						  @"Deine Mudda erzählt dir deine Mudda Witze.",
						  @"McDonalds hat angerufen, deine Mudda hängt besoffen in der Rutsche fest.",
						  @"Deine Mudda ist so fett sie wurde in aqualand getauft.",
						  @"Deine Mudda springt von Hochhaus und singt: Wenn der Mond in mein Ghetto Kracht.",
						  @"Deine Mudda kommt bei 9 live durch und verliert.",
						  @"Deine Mudda hat Schulden am Kaugummiautomat.",
						  @"Deine Mudda schluckt mehr als ein 7er.",
						  @"Deine Mudda zieht LKW´s bei DSF.",
						  @"Deine Mudda ist Freeware.",
						  @"Deine Mudda rotzt dir in die Fresse und schreit Aquaknarre.",
						  @"Deine Mudda ist so dumm - sie guckt bei einer Glastür durchs Schlüsselloch.",
						  @"Deine Mudda schmiert Senf auf´n Fernseher, damit das Bild schärfer wird.",
						  @"Deine Mudda ist so fett, dass sie mit ihren Arschbacken Beatbox spielen kann.",
						  @"Deine Mudda ist so dumm, sie wartet darauf, dass das Stopschild grün wird.",
						  @"Deine Mudda ist so fett, sie rasiert sich mit einem Rasenmäher.",
						  @"Deine Mudda schubst kleine Entchen in den Teich.",
						  @"Deine Mudda schreit bei jedem Poker MauMau.",
						  @"Deine Mudda ist so doof, sie fragt den Vibrator warum er so zittert.",
						  @"Deine Mudda lässt sich im Winter für Kinder als Rodelberg anmieten.",
						  @"Deine Mudda macht das döööt bei TV Total.",
						  @"Wenn deine Mudda auf dem Bauch liegt, bekommt sie Höhenangst.",
						  @"Deine Mudda ist so fett, sie wurde im Aqualand getauft.",
						  @"Deine Mudda stürzt öfters ab als Windows.",
						  @"Deine Mudda ist so fett, selbst DHL könnte sie nicht versenden.",
						  @"Deine Mudda ist soo fett, wenn sie auf die Waage geht, steht da Fortsetzung folgt....",
						  @"Deine Mudda ist so fett, sie arbeitet als Hüpfburg auf Kindergeburtstagen.",
						  @"Deine Mudda die passt scho, aber halt net durch die Tür.",
						  @"Deine Mudda hat im Wald ein Lebkuchenhaus.",
						  @"Deine Mudda ist so fett, die arbeitet als Gegengewicht im Aufzug.",
						  @"Deine Mudda ist wie ein schlechter Torwart. Sie lässt immer einen rein.",
						  @"Deine Mudda ist so dumm,die sitzt auf'm Fernseher und guckt Couch.",
						  @"Deine Mudda duscht mit einem Regenschirm.",
						  @"Deine Mudda ist so dumm, sie verläuft sich in einer Telefonzelle.",
						  @"Deine Mudda muss eine Abgasplakette tragen wenn sie in die Stadt will.",
						  @"Deine Mudda hat Hausverbot bei Fressnapf.",
						  @"Deine Mudda ist so fett, sie füllt die Badewanne und dreht dann erst das Wasser auf.",
						  @"Deine Mudda ist soo fett, wenn man ihr auf den Arsch klatscht, kann man auf der 3. Welle weitersurfen..",
						  @"Deine Mudda lebt vom Flaschenpfand.",
						  @"Deine Mudda zieht sich Flip Flops mit nem Schuhlöffel an.",
						  @"Deine Mudda ist so fett, wenn sie furzt klagt sie Al Gore wegen globaler Klimaerwährmung an.",
						  @"Deine Mudda hat gestern den Führerschein für den Einkaufswagen gemacht.",
						  @"Deine Mudda pisst gegen den Wind und freut sich.",
						  @"Deine Mudda ist so dumm, die buddelt stundenlang mit ner Plastikschaufel aufm Betonboden.",
						  @"Deine Mudda wohnt im Auto und sagt dir die Richtung an.",
						  @"Deine Mudda ist die Hauptattraktion von Burger King.",
						  @"Deine Mudda schreit beim Kacken BomChickaWahWah.",
						  @"Deine Mudda trinkt Bier, aber nur aus Eimern.",
						  @"Deine Mudda isst Würmer auf RTL.",
						  @"Deine Mudda ist so fett, sie braucht einen Flugzeugträger als Sonnenstuhl.",
						  @"Deine Mudda kann das Lied We will rock you pfurzen - Und das alleine mit hren Speckfalten.",
						  @"Deine Mudda ist so fett, wenn sie auf dem Bauch liegt kriegt sie Höhenangst.",
						  @"Deine Mudda lässt Tische auf Pro7 fliegen.",
						  @"Deine Mudda verbiegt Löffel auf Pro 7.",
						  @"Deine Mudda spricht die Synchronstimme von Arnold Schwarzenegger.",
						  @"Deine Mudda furzt in der U-Bahn und sagt du warsts.",
						  @"Deine Mudda sagt zu dir: Ich bin deine Mudda, du Hurensohn.",
						  @"Deine Mudda is so häßlich, ihre Mudda hat sie früher mit der Steinschleuder gefüttert.",
						  @"Deine Mudda ist so dumm, sie würzt ihr Essen mit Pfefferspray.",
						  @"Deine Mudda wird mit Polizeieskorte über die Autobahn transportiert.",
						  @"Deine Mudda macht die Luftballons von kleinen Kindern kaputt.",
						  @"Deine Mudda klaut Kindern die Lollies aus dem Mund.",
						  @"Deine Mudda hat mehr Säcke gesehen als ein Musterungsarzt.",
						  @"Deine Mudda ist so fett, dass sie einen eigenen Eintrag im Atlas bekommt.",
						  @"Deine Mudda ist wie MySpace, jeder war schon mal drauf.",
						  @"Deine Mudda hat angerufen, du sollst nach Hause kommen. Im Puppenhaus brennt noch Licht.",
						  @"Deine Mudda ist so fett, dass sogar Buddha aussieht wie ein Bodybuilder.",
						  @"Deine Mudda lutscht die Urinsteine aus der Pissrinne.",
						  @"Deine Mudda ist so fett, man benutzt ihre Speckfalten als Sauna.",
						  @"Deine Mudda ist so fett, sie ist an der Globalen Erderwärmung Schuld.",
						  @"Deine Mudda spielt Counter Strike mit nem Lenkrad.",
						  @"Deine Mudda spielte in Harry Potter den Hagrid.",
						  @"Deine Mudda verkauft im Sommer Schatten.",
						  @"Deine Mudda backt Pommes auf der Heizung.",
						  @"Deine Mudda ist so fett, die hat ne eigene Postleitzahl.",
						  @"Deine Mudda klaut Freibier.",
						  @"Deine Mudda geht mit nem MP3-Player in die Disko.",
						  @"Deine Mudda steht im Pokedex.",
						  @"Deine Mudda ist wie ne S-Bahn,da darf jeder mal rein.",
						  @"Deine Mudda ist so hässlich, dass vor ihr selbst ein Blinder wegrennt.",
						  @"Deine Mudda ist so fett, die hält ne Familienpizza fürn Snack für zwischendurch.",
						  @"Deine Mudda hat die Maße 90/60/90, natürlich pro Bein.",
						  @"Deine Mudda hat Dauerkarten fürs Arbeitsamt.",
						  @"Deine Mudda hat nur ein Auge und sagt: Mit dem Zweiten sieht man besser.",
						  @"Deine Mudda putzt sich ihre Zähne mit ner Drahtbürste.",
						  @"Deine Mudda ist so fett, auf ihrem Schatten können 10 Flugzeuge landen.",
						  @"Deine Mudda hat bei World of Warcraft nen Level 70 Nachtelf-Irokesen.",
						  @"Deine Mudda ist so fett, sie braucht ein Navigationssystem, um ihren Bauchnabel zu finden.",
						  @"Deine Mudda ist so fett, das sie ihre Fettspalten Pennern im Winter ausleiht, als warmen Schlafplatz.",
						  @"Deine Mudda hat nur einen Arm und schwimmt im Kreis.",
						  @"Deine Mudda ist so dumm, die stolpert übers schnurlose Telefon.",
						  @"Deine Mudda ihr arsch ist so fett, dass 3 LKWs darauf wenden können.",
						  @"Deine Mudda sammelt Pilze, aber nicht im Wald.",
						  @"Deine Mudda ist so dumm, die kauft bei eBay Wireless-LAN-Kabel.",
						  @"Deine Mudda sitzt sechs Monate in Untersuchungshaft, weil sie betrunken Autoscooter gefahren ist.",
						  @"Deine Mudda hat zum zweiten Mal in Folge die Lumberjack-Championchips gewonnen.",
						  @"Deine Mudda ist so blöd, die muss sich 17 Freunde einladen damit sie einen Film ab 18 sehen darf.",
						  @"Deine Mudda steht um 7:55 Uhr vorm Aldi und singt: This is the Final Countdown.",
						  @"Deine Mudda ist so fett, die muss bei Rapidshare in 100 Parts geuppt werden.",
						  @"Deine Mudda trinkt Bongwasser zum Frühstück.",
						  @"Deine Mudda sitzt im Cola-Automat und gibt Wechselgeld.",
						  @"Deine Mudda ist so fett, die liegt 5 Minuten am Strand und dann kommt Greenpeace und singt Schiebt den Wal ....",
						  @"Deine Mudda ist so fett wenn ihr Peeper ausgeht denken alle dass sie jeden moment platzt.",
						  @"Deine Mudda ist so fett ihr Spitzname ist VERDAMMT.",
						  @"Deine Mudda ist so fett wir sind gerade in ihr drin.",
						  @"Deine Mudda ist so fett Leute joggen zum Training um sie herum.",
						  @"Deine Mudda ist so fett sie ging ins Kino und saß neben jedem.",
						  @"Deine Mudda ist so fett sie ist jetzt Naturschutzgebiet für Falken geworden.",
						  @"Deine Mudda ist so fett sie sprang in den Ozean und Spanien dankte ihr für die neue Welt.",
						  @"Deine Mudda ist so fett als sie lag am Strand sind Kinder um sie herumgerannt und haben Free Willy gerufen.",
						  @"Deine Mudda ist so fett wenn sie mit jemandem schläft muß sie Richtungen angeben.",
						  @"Deine Mudda ist so fett sie ging in ein Restaurant, guckte sich die Speisekarte an und sagte: Okay!.",
						  @"Deine Mudda ist so fett wenn sie einen gelben Regenmantel anhat rufen alle Taxi!.",
						  @"Deine Mudda ist so fett sie muß sich ihre Hosen auf der Straße bügeln.",
						  @"Deine Mudda ist so fett sie muß sich ihre Hosen ausziehen um in die Taschen zu kommen.",
						  @"Deine Mudda ist so fett sie mußte ins Aqua-Land gehen um getauft zu werden.",
						  @"Deine Mudda ist so fett sie ging über die 4th Avenue und landete auf der 9th..",
						  @"Deine Mudda ist so fett als Bungee-Jumping machte hat sie die Brücke mitruntergerissen.",
						  @"Deine Mudda ist so fett wenn sie sich auf eine Waage stellt steht Bitter einer nach dem anderen drauf.",
						  @"Deine Mudda ist so fett wenn sie sich auf eine Waage stellt steht Fortsetzung folgt.. drauf.",
						  @"Deine Mudda ist so fett wenn sie sich auf eine Waage stellt steht Bitte keine Bullen.. drauf.",
						  @"Deine Mudda ist so fett ihr Nacken sieht aus wie 2 Hot-Dogs.",
						  @"Deine Mudda ist so fett sie hat ihre eigene Postleitzahl.",
						  @"Deine Mudda ist so fett sie sieht aus als ob sie Autos schmuggelt.",
						  @"Deine Mudda ist so fett Gott konnte kein Licht machen bis sie wegging.",
						  @"Deine Mudda ist so fett die Nasa mußte einen Satelit in ihren Orbit schießen.",
						  @"Deine Mudda ist so fett selbst Bill Gates kann ihre Fettabsaugung nicht bezahlen.",
						  @"Deine Mudda ist so fett ihre beine sind wie schlechte Milch - sie sind weiß und stinken.",
						  @"Deine Mudda ist so fett du mußt sie durch Mehl rollen damit man den nassen Punkt zum ficken findet.",
						  @"Deine Mudda ist so fett sie wacht in Teilen auf.",
						  @"Deine Mudda ist so fett wenn sie in einen Zoo geht versuchen Leute SIE zu reiten.",
						  @"Deine Mudda ist so fett sie war ein Fehlversuch für Gottes Bowlingball.",
						  @"Deine Mudda ist so fett sie liegt am Strand und keiner bekommt Sonne.",
						  @"Deine Mudda ist so fett wenn sie Bungee-Jumping macht fällt sie direkt in die Hölle.",
						  @"Deine Mudda ist so fett sie sprang in die Luft und blieb stecken.",
						  @"Deine Mudda ist so fett ihr Abschlußfoto mußte von einem Helicopter geschossen werden.",
						  @"Deine Mudda ist so fett immer wenn sie auf Zehenspitzen geht findet immer sie Öl.",
						  @"Deine Mudda ist so fett sie fiel hin und schuf den Grand Canyon.",
						  @"Deine Mudda ist so fett sie saß am Strand und GreenPeace schmiss sie ins Meer.",
						  @"Deine Mudda ist so fett sie benutzt einen Videorecorder als Peeper.",
						  @"Deine Mudda ist so fett wenn sie in einem Heißluftballon sitzt siehts aus als ob is Strumpfhosen anhat.",
						  @"Deine Mudda ist so fett sie mußten die Badewanne einfetten um sie herauszubekommen.",
						  @"Deine Mudda ist so fett sie hat eine Laufmasche in ihrer Jeans.",
						  @"Deine Mudda ist so fett einer benutzte ihr Gummiband in ihrer Unterhose zum Bungee-Jumping.",
						  @"Deine Mudda ist so fett sie muß zwei Flugtickets kaufen.",
						  @"Deine Mudda ist so fett sie beeinflußt das Wetter.",
						  @"Deine Mudda ist so fett als ich versuchte um sie herum zu fahren hat mein Spritt nicht gereicht.",
						  @"Deine Mudda ist so fett die Tiere im Zoo füttern sie.",
						  @"Deine Mudda ist so fett sie steht immer in zwei Zeitzohnen.",
						  @"Deine Mudda ist so fett man muß den Türrahmen einfetten und einen Keks ins Zimmerlegen nur damit man sie reinbekommt.",
						  @"Deine Mudda ist so fett sie kann ihre eigenen Schuhe nicht zumachen.",
						  @"Deine Mudda ist so fett wenn sie geht lößt sie Autoalarmanlagen aus.",
						  @"Deine Mudda ist so fett sie kann ihre Hintertaschen der Hose nicht erreichen.",
						  @"Deine Mudda ist so fett die einzigen Bilder von ihr sind von einem Satteliten aus aufgenommen.",
						  @"Deine Mudda ist so fett sie benutzt eine Matratze als Tampon.",
						  @"Deine Mudda ist so fett sie wurde im Meer getauft.",
						  @"Deine Mudda ist so fett wenn sie an einer Linksabbiegerampel steht bekommt sie den grünen Pfeil.",
						  @"Deine Mudda ist so fett wenn sie von einem Bus angefahren wird sagt sie: Wer hat den Stein geworfen?.",
						  @"Deine Mudda ist so fett die Nationale Wetteragentur müssen Namen für ihre Pfürze erfinden.",
						  @"Deine Mudda ist so fett man braucht eine Landkarte um ihr Arschloch zu finden.",
						  @"Deine Mudda ist so fett man braucht ein Flugzeug um an das andere Ende zu kommen.",
						  @"Deine Mudda ist so fett ihr Gürtel ist der Äquator.",
						  @"Deine Mudda ist so fett sie braucht einen Boomerang um sich den Gürtel umzuschnallen.",
						  @"Deine Mudda ist so fett sie kann den Mond ersetzen.",
						  @"Deine Mudda ist so fett mit ihrem Auto braucht sie alle Spuren.",
						  @"Deine Mudda ist so fett, wenn die aus dem Haus geht denken alle es ist Sonnenfinsternis!.",
						  @"Deine Mudda ist so fett im Kino bekommt sie Gruppenrabatt..",
						  @"Deine Mudda ist so dumm wenn sie das FSK ab 18 Schild liest lädt sie sich erstmal 17 Freunde ein.",
						  @"Deine Mudda ist so dumm sie hat jedem gesagt das sie intelligment ist weil sie nicht lesen kann.",
						  @"Deine Mudda ist so dumm sie ist in einem Supermarkt eingesperrt worden und verhungerte.",
						  @"Deine Mudda ist so dumm sie hat versucht M&Ms alphabetisch zu ordnen.",
						  @"Deine Mudda ist so dumm sie könnte über ein schnurloses Telefon fallen.",
						  @"Deine Mudda ist so dumm sie verkaufte ihr Auto für die Benzinrechnung.",
						  @"Deine Mudda ist so dumm sie kaufte ein solarbetriebenes Flash-Light.",
						  @"Deine Mudda ist so dumm sie fragt dich sogar wie ist die Nummer der 110?.",
						  @"Deine Mudda ist so dumm sie stahl kostenloses Brot.",
						  @"Deine Mudda ist so dumm neben ihr sehen Beavis&Butthead wie Nobelpreisträger aus.",
						  @"Deine Mudda ist so dumm wenn du direkt neben ihr stehst hörst du die Ozeanwellen.",
						  @"Deine Mudda ist so dumm sie sitzt auf dem Fernseher und guckt aufs Sofa.",
						  @"Deine Mudda ist so dumm sie dachte Boys II Men ist eine Kindertagesstätte.",
						  @"Deine Mudda ist so dumm sie kaufte sich eine Videokamera um Filme im Fernsehen aufzunehmen.",
						  @"Deine Mudda ist so dumm sie wollte den Bus 240 nehmen und nahm statt dessen den Bus 120 zweimal.",
						  @"Deine Mudda ist so dumm, die läßt sich von einem parkendem Auto überfahren..",
						  @"Deine Mudda ist so dumm, die läßt Wasser anbrennen..",
						  @"Deine Mudda ist so hässlich sie wollte an einem Hässlichkeitskontest mitmachen und die Organisatoren sagten Sorry, keine Profis!.",
						  @"Deine Mudda ist so hässlich bei ihrer Geburt sagte die Mudda Was für ein Schatz und der Vater sagte Ja! Lass uns ihn begraben!.",
						  @"Deine Mudda ist so hässlich man drückt ihren Kopf in Teig um Gorilla-Kekse zu machen.",
						  @"Deine Mudda ist so hässlich man gab ihr kein Kostü als sie sich für Star Wars bewarb.",
						  @"Deine Mudda ist so hässlich anstatt das Bungee-Seil um die Teile zu binden, binden sie ihr es um den Hals.",
						  @"Deine Mudda ist so hässlich sie bekommt 364 Extra-Tage um sich für Halloween zu verkleiden.",
						  @"Deine Mudda ist so hässlich wenn sie in eine Bank kommt stellen sie die Überwachungskameras aus.",
						  @"Deine Mudda ist so hässlich ihre Mudda musste besoffen sein um sie zu stillen.",
						  @"Deine Mudda ist so hässlich man band ihr damals ein Steak um den Hals damit wenigstens die Hunde mit ihr spielten.",
						  @"Deine Mudda ist so hässlich Bill Clinton legte Halloween auf ihren Geburtstag.",
						  @"Deine Mudda ist so hässlich wenn sie strippt bekommt sie Geld damit sie sich wieder anzieht.",
						  @"Deine Mudda ist so hässlich sie bringt eine Zwiebel zum heulen.",
						  @"Deine Mudda ist so hässlich sie wollte ein Bad nehmen und das Wasser floh.",
						  @"Deine Mudda ist so hässlich sie guckte aus dem Fenster und wurde verhaftet.",
						  @"Deine Mudda ist so hässlich sie verwandelte Medusa in Stein.",
						  @"Deine Mudda ist so hässlich wenn sie am Strand sitzt versuchen Katzen sie zu vergraben.",
						  @"Deine Mudda ist so hässlich ihr Vater nimmt sie mit zur Arbeit damit er ihr keinen Abschiedskuss geben muss.",
						  @"Deine Mudda heißt Harry und ist die stärkste im Knast.",
						  @"Deine Mudda lässt den Salat anbrennen.",
						  @"Deine Mudda ist so fett, ihre Blutgruppe heißt Nutella.",
						  @"Deine Mudda schwitzt beim Kacken.",
						  @"Deine Mudda ist soooo fett, wenn sie auch die Waage steht wird deine Handynummer angezeigt.",
						  @"Hat deine Mudda eigentlich noch den Job im Kino? Als Leinwand?.",
						  @"Deine Mudda läuft bei Super Mario nach links….",
						  @"Deine Mudda klaut bei KIK... und verlangt den Kassenzettel.",
						  @"Deine Mudda ist so haarig, sie spricht nur wookie.",
						  @"Deine Mudda ist Linksträger.",
						  @"Deine Mudda steht vorm KIK und schreit: ICH BIN BILLIGER.",
						  @"Ich war heute früh schon 10 km joggen... einmal um deine Mudda rum.",
						  @"Deine Mudda steht morgens um fünf vor acht vorm Aldi und singt “it’s the final countdown…”.",
						  @"Deine Mudda schubbst Kinder vom Fahrrad und schnüffelt am Sattel.",
						  @"Deine Mudda fährt den Zug von Jim Knopf.",
						  @"Deine Mudda ist so fett, die piept wenn sie rückwärts geht.",
						  @"Deine Mudda heißt Andreas und zieht nachts bei DSF Lastwagen.",
						  @"Deine Mudda ist so fett, sie benutzt Google Earth, um Passfotos zu machen.",
						  @"Wenn deine Mudda am Strand liegt, kommt Greenpeace und will sie wieder ins Meer schieben.",
						  @"Wenn Dummheit Fahrrad fahren könnte müsste deine Mudda bergauf bremsen.",
						  @"Jeder war schon drin, aber keiner gibt’s zu.",
						  @"Deine Mudda singt bei Motörhead.",
						  @"Deine Mudda ist so fett, sie ging in ein Restaurant, sah sich die Speisekarte an und sagte: “Okay”.",
						  @"Deine Mudda isst Kürbisjoghurt mit ganzen Früchten.",
						  @"Deine Mudda ist der Endgegner.",
						  @"Deine Mudda zerreisst Telefonbücher bei Wetten Dass…?.",
						  @"Deine Mudda richtet bei RTL Wohnungen ein.",
						  @"Deine Mudda singt beim scheißen “Drop it like it´s hot”.",
						  @"Deine Mudda ist so dumm, die will bei Apple Obst kaufen.",
						  @"Deine Mudda hat so lange Achselhaare, dass es aussieht, als hätte sie zwei Hippies im Schwitzkasten.",
						  @"Deine Mudda wirft ne matschige Orange auf den Boden und schreit: “LOS PIKATCHU!”.",
						  @"Deine Mudda bellt wenns klingelt.",
						  @"Deine Mudda rennt nackt durchs Dorf und schreit: “DAS IST SPARTA!”.",
						  @"Deine Mudda macht Kniebeugen im Gurkenfeld….",
						  @"Deine Mudda kämmt sich ihr Brusthaar.",
						  @"Deine Mudda macht hinterm Aldi Armdrücken um Flaschenpfand.",
						  @"Deine Mudda arbeitet auf nem Fischkutter als Gestank.",
						  @"Deine Mudda stinkt nach Bockwurstwasser.",
						  @"Deine Mudda macht mehr 3er als BMW.",
						  @"Deine Mudda ist wie ne Packung Böller, für nen Euro kannste 5x knallen.",
						  @"Deine Mudda lispelt beim Chatten.",
						  @"Deine Mudda ist so dumm, die rennt dem Müllwagen hinterher und schreit: “KAMELLE”.",
						  @"Deine Mudda schubst kleine Kinder vom Fahrrad und riecht am Sattel.",
						  @"Deine Mudda sitzt im Mülleimer und singt: “Its my life”.",
						  @"Wenn deine Mudda sich auf die Waage stellt, zeigt diese meine Handynummer an.",
						  @"Deine Mudda macht mit Google Earth Passfotos.",
						  @"Deine Mudda ist so dumm, die lässt sich von nem parkenden Auto überfahren.",
						  @"Deine Mudda ist so hässlich, die bringt sogar eine Zwiebel zum Heulen.",
						  @"Deine Mudda kommt bei 9Live durch und verliert.",
						  @"Deine Mudda piept beim Rückwärtslaufen.",
						  @"Deine Mudda isst Kürbisjurghurt mit ganzen Früchten.",
						  @"Deine Mudda war die Haarigste im Zoo.",
						  @"Deine Mudda ist so fett, wenn sie am Fernseher vorbei geht verpasst du alle drei Teile von Herr der Ringe.",
						  @"Deine Mudda zeigt auf ihr Spiegelbild und schreit “Pablo”.",
						  @"Deine Mudda is so Dumm, die verkauft im Wald Stöcke.",
						  @"Deine Mudda lutscht Klosteine.",
						  @"Deine Mudda Hat ein Job als Hüpfburg.",
						  @"Wenn deine Mudda was mit gelben Klamotten ausm Flugzeug springt, denken die Kinder in Asien die Sonne geht auf.",
						  @"Deine Mudda gewinnt unter 40 Männern beim Wettwichsen.",
						  @"Deine Mudda ist wie die Essiggurke auf dem Hamburger, überall ist sie dabei aber keiner will sie.",
						  @"Deine Mudda klaut Freibier.",
						  @"Deine Mudda steht vorm Dönerladen und sagt: “Nimm mich mit, ich bin auch fett und saftig.”.",
						  @"Deine Mudda kackt vor Aldi weil an der Tür bitte drücken steht.",
						  @"Der TOD hat wollte mal deine Mudda mittnehmen aber sie hat ihn schnell im schwitzkasten genommen und seit dem schläft der TOD mit Licht und guckt immer ob deine Mudda im schrank ist.",
						  @"Deine Mudda steht auf der Straße und wird von Pennern mit Kleingeld beworfen.",
						  @"Deine Mudda wird öfters geknallt als die Türe vom Arbeitsamt.",
						  @"Deine Mudda hat nur ein Bein und sagt: “Tunnel mich.”.",
						  @"Deine Mudda lacht beim Kacken.",
						  @"Deine Mudda ist so dumm, sie will auf den Nato-Gipfel klettern.",
						  @"Deine Mudda heißt Bernd und ist der stärkste im Knast.",
						  @"Deine Mudda ist so dumm, die klaut Gratisluftballons.",
						  @"Deine Mudda zieht LKW auf DSF.",
						  @"Deine Mudda ist so fett, in ihrer Umlaufbahn bewegen sich zwei kleinere Frauen.",
						  @"Deine Mudda macht schlechten Salat!",
						  @"Deine Mudda ist so fett, sie hat eine eigene Postleitzahl.",
						  @"Deine Mudda ist so fett, als sie neulich ins Kino ging saß sie neben jedem jedem.",
						  @"Deine Mudda hat Blutgruppe Frittenfett.",
						  @"Deine Mudda arbeitet aufm Kutter - als Geruch.",
						  @"Deine Mudda legt Tarotkarten auf 9-live.",
						  @"Deine Mudda piept beim Rückwärtsgehen.",
						  @"Deine Mudda riecht nach Bockwurstwasser.",
						  @"Deine Mudda macht mehr 3er als BMW und schluckt mehr als ein 7er.",
						  @"Deine Mudda schubst kleine Mädchen vom Fahrrad und riecht am Sattel.",
						  nil];
	
	FXiDataCore *dataCore = [FXiDataCore sharedInstance];
	
	NSManagedObjectContext *context = [dataCore managedObjectContext];
	

	int counter = 0;
	for (NSString *str in lolimport)
	{
		FXManagedJoke *joke = [NSEntityDescription insertNewObjectForEntityForName:@"Joke" inManagedObjectContext: context];	
		[joke setRating: [NSNumber numberWithInt: 0]];	
		[joke setUnlockLevel: [NSNumber numberWithInt: counter++%5]];
		
		NSLog(@"joke unlock level: %i", [[joke unlockLevel] intValue]);
		
		[joke setJokeText: str];
	}
	

	[dataCore saveContext];
	
	[defs setBool: YES forKey: @"databaseCreated"];
	[defs synchronize];
}

@end
